---
title: "Tarea 3 ML"
author: "Sebastian Alzate Vargas"
date: "Febrero 11/2021"
output:
  pdf_document: default
  html_document: default
---

# Probelama 1
Considere la matriz $$A=
\begin{pmatrix}
2  &  -1  \\
-1  &  2
\end{pmatrix}$$ 

a. Muestre que $A$ es definida positiva

b. Encuentre $A^{1/2}$

## Solución 
Sea $y$ un vector diferente de cero

\begin{align*}
y'Ay &= 
\begin{pmatrix}
y_1 & y_2
\end{pmatrix}
\begin{pmatrix}
2  &  -1  \\
-1  &  2
\end{pmatrix}
\begin{pmatrix}
y_1 \\
y_2
\end{pmatrix}\\ \\
&= \begin{pmatrix}
2y_1-y_2 & -y_1+2y_2
\end{pmatrix}
\begin{pmatrix}
y_1  \\
y_2
\end{pmatrix}\\
&= 2y_1^2 -y_1y_2 - y_1y_2 + 2y_2^2 \\
&= y_1^2 + y_2^2 + (y_1-y_2)^2
\end{align*}

El resultado anterior siempre es mayor estricto que cero pues $y_1,y_2$ son diferentes de cero, es decir, $y_1^2 + y_2^2>0$.


b. Para encontrar $A^{1/2}$ debemos tener los autovalores y autovectores de la matriz $A$. Los cuales son:

\begin{align*}
    |A- \lambda I| &= 
        \begin{vmatrix}
    2 - \lambda & -1 \\ 
    -1          & 2-\lambda 
    \end{vmatrix}\\
    &= (2-\lambda)^2-1\\
    &=4-4\lambda-\lambda^2-1\\
    &= \lambda^2 - 4\lambda +3 \\
    &=(\lambda-3)(\lambda-1)=0
\end{align*}

tenemos $\lambda_1=3$ y $\lambda_2=1$. Ahora hallemos los autovectores


Autovector asociado a $\lambda_1=3$

\begin{align*}
    &(A- \lambda_1 I)x=0\\
    &\begin{pmatrix}
    -1 & -1 \\ 
    -1  & -1 
    \end{pmatrix}
    \begin{pmatrix}
    x_1\\
    x_2
    \end{pmatrix}
    = \begin{pmatrix}
    0 \\0
    \end{pmatrix} \\
    & \begin{pmatrix}
    -x_1-x_2\\
    -x_1-x_2
    \end{pmatrix}
    =\begin{pmatrix}
    0 \\0
    \end{pmatrix} \\
\end{align*}

Así, $x_1=-x_2$, Si $x=1$ entonces $x_2=-1$. Un autovector normalizado asociado a $\lambda_1$ es  $\frac{1}{\sqrt{2}}(1,-1)'$

Autovector asociado a $\lambda_2=1$

\begin{align*}
    &(A- \lambda_2 I)x =0 \\
    &\begin{pmatrix}
    1 & -1 \\ 
    -1  & 1 
    \end{pmatrix}
    \begin{pmatrix}
    x_1\\
    x_2
    \end{pmatrix}
    = \begin{pmatrix}
    0 \\0
    \end{pmatrix} \\
    & \begin{pmatrix}
    x_1-x_2\\
    -x_1+x_2
    \end{pmatrix}
    = \begin{pmatrix}
    0 \\0
    \end{pmatrix} \\
\end{align*}


Así, $x_1=x_2$, Si $x=1$ entonces $x_2=1$. Un autovector normalizado asociado a $\lambda_2$ es  $\frac{1}{\sqrt{2}}(1,1)'$

Ahora podemos formar la matriz $C$, que esta compuesta por los autovectores y la matriz $D$ que esta compuesta por los autovalores.
$$  C= \frac{1}{\sqrt{2}}\begin{pmatrix}
    1&1\\
    -1&1\\
    \end{pmatrix}, \ \  D= \begin{pmatrix}
    3 & 0 \\
    0 & 1 
    \end{pmatrix} $$

Finalmente,

\begin{align*}
     A^\frac{1}{2} &= CD^{1/2}C' \\
      &=\frac{1}{\sqrt{2}}\begin{pmatrix}
    1&1\\
    -1&1\\
    \end{pmatrix}
    \begin{pmatrix}
    \sqrt{3} & 0 \\
    0 & \sqrt{1} 
    \end{pmatrix} 
      \frac{1}{\sqrt{2}}\begin{pmatrix}
    1&1\\
    -1&1\\
    \end{pmatrix}'\\ \\
    &=\frac{1}{\sqrt{2}\sqrt{2}}\begin{pmatrix}
    1&1\\
    -1&1\\
    \end{pmatrix}
    \begin{pmatrix}
    \sqrt{3} & 0 \\
    0 & \sqrt{1} 
    \end{pmatrix} 
      \begin{pmatrix}
    1&-1\\
    1&1\\
    \end{pmatrix} \\ \\
    &=\frac{1}{2}\begin{pmatrix}
    1&1\\
    -1&1\\
    \end{pmatrix}
    \begin{pmatrix}
    \sqrt{3}&-\sqrt{3}\\
    1&1
    \end{pmatrix} \\ \\ 
    &= \frac{1}{2} \begin{pmatrix}
    \sqrt{3}+1 & -\sqrt{3} + 1 \\
    \sqrt{3}+1 &  \sqrt{3}+1 
    \end{pmatrix}
\end{align*}

# Problema 2
Sea $$A =
\begin{pmatrix}
1   & 0 & x \\
0   & 1 & 0 \\
x   & 0 & 1 \\
\end{pmatrix}$$

Encuentre $\frac{\partial \log\vert\pmb{A}\vert}{\partial x}$ drectamente y utilizando el teorema de clase

## Solución
El teorema nos dice que $\dfrac{\partial \log\vert A\vert}{\partial x}=tr\left(A^{-1} \dfrac{\partial A}{\partial x} \right)$

Tenemos 

\begin{align*}
    \dfrac{\partial A}{\partial x}=\begin{pmatrix}
    0 & 0 & 1\\
    0 & 0 & 0\\
    1 & 0 & 0
    \end{pmatrix}
\end{align*}

Ahora hallemos su inversa por el método de Gauss  o matriz aumentada

\[ \left(
\begin{array}{ccc|ccc}
1 & 0 & x & 1 & 0 & 0\\
0 & 1 & 0 & 0 & 1 & 0\\
x & 0 & 1 & 0 & 0 & 1
\end{array}
\right)\underrightarrow{-xR_1+R_3 \rightarrow R_3 }\]

\[ \left(
\begin{array}{ccc|ccc}
1 & 0 & x & 1 & 0 & 0\\
0 & 1 & 0 & 0 & 1 & 0\\
0 & 0 & 1-x^2 & -x & 0 & 1
\end{array}
\right)  \underrightarrow{\frac{R_3}{1-x^2} \rightarrow R_3 }\]

\[ \left(
\begin{array}{ccc|ccc}
1 & 0 & x & 1 & 0 & 0\\
0 & 1 & 0 & 0 & 1 & 0\\
0 & 0 & 1 & \frac{-x}{1-x^2} & 0 & \frac{1}{1-x^2}
\end{array}
\right)  \underrightarrow{-xR_3+R_1 \rightarrow R_1 }\]

\[ \left(
\begin{array}{ccc|ccc}
1 & 0 & 0 & 1+\frac{x^2}{1-x^2} & 0 & \frac{-x}{1-x^2}\\
0 & 1 & 0 & 0 & 1 & 0\\
0 & 0 & 1 & \frac{-x}{1-x^2} & 0 & \frac{1}{1-x^2}
\end{array}
\right) \]

\[ \left(
\begin{array}{ccc|ccc}
1 & 0 & 0 & \frac{-1}{x^2-1} & 0 & \frac{x}{x^2-1}\\
0 & 1 & 0 & 0 & 1 & 0\\
0 & 0 & 1 & \frac{x}{x^2-1} & 0 & \frac{-1}{x^2-1}
\end{array}
\right) \]


Entonces,
\[ A^{-1}=\left(
\begin{array}{ccc}
\frac{-1}{x^2-1} & 0 & \frac{x}{x^2-1}\\
 0 & 1 & 0\\
\frac{x}{x^2-1} & 0 & \frac{-1}{x^2-1}
\end{array}
\right) \]

Ahora encontremos $tr \left( A^{-1} \dfrac{\partial A}{\partial x} \right)$

\begin{align*}
     tr\left(A^{-1} \dfrac{\partial A}{\partial x}\right)&=tr\left(\begin{pmatrix}
    \frac{-1}{x^2-1} & 0 & \frac{x}{x^2-1}\\
 0 & 1 & 0\\
\frac{x}{x^2-1} & 0 & \frac{-1}{x^2-1}
    \end{pmatrix}
    \begin{pmatrix}
    0 & 0 & 1\\
    0 & 0 & 0\\
    1 & 0 & 0
    \end{pmatrix} \right)\\
     &=tr\begin{pmatrix}
    \frac{x}{x^2-1} & 0 & \frac{-1}{x^2-1}\\
    0 & 0 & 0\\
    \frac{-1}{x^2-1} & 0 & \frac{x}{x^2-1}
    \end{pmatrix}\\
    &= \frac{x}{x^2-1}+\frac{x}{x^2-1}\\
    &= \frac{2x}{x^2-1}
\end{align*}

Directamente:

\begin{align*}
    A &=
\begin{vmatrix}
1   & 0 & x \\
0   & 1 & 0 \\
x   & 0 & 1 \\
\end{vmatrix}\\
&=1\begin{vmatrix} 1 & 0 \\  0 & 1 \end{vmatrix} - 0\begin{vmatrix} 0 & 0 \\  x & 1 \end{vmatrix}+1\begin{vmatrix} 0 & 1 \\  x & 0 \end{vmatrix}\\
    &= 1\cdot 1 -0+x(-x)\\
    &=1-x^2
\end{align*}

Luego, 

\begin{align*}
   \dfrac{ \partial \log |A|}{ \partial x}&=\dfrac{ \partial \log (1-x^2)}{ \partial x}\\
   &= \dfrac{-2x}{1-x^2}\\
   &=  \dfrac{2x}{x^2-1}
\end{align*}

# Problema 3
Sea $Y = \begin{pmatrix} Y_1& Y_2 \end{pmatrix}'$ con $E[Y_1]=E[Y_2]=0$, $var(Y_1)=1$, $var(Y_2)=4$ y $cov(Y_1,Y_2)=-2$. Sea $$A = \begin{pmatrix} 2 & -1 \\ 0 & 3 \end{pmatrix}$$

Verifique el teorema (5.1.10) parte i. directamente.

## Solución
El teorema nos dice que $cov(AY)=A\Sigma A'$. Hallemos primero $cov(AY)$
$$AY = \begin{pmatrix}
2 & -1 \\
0 & 3
\end{pmatrix} \binom{Y_1}{Y_2} = \binom{2Y_1-Y_2}{3Y_2}$$
Ahora podemos encontrar el esperado del vector anterior 
\begin{align*}
    \mu_{AY} &= \mathbb{E}\binom{2Y_1-Y_2}{3Y_2} \\
    &= \binom{\mathbb{E}(2Y_1-Y_2)}{\mathbb{E}(3Y_2)}\\
    &= \binom{2\mathbb{E}(Y_1)-\mathbb{E}(Y_2)}{3\mathbb{E}(Y_2)} \\
    &= \binom{0}{0}
\end{align*}
Así,
\begin{align*}
    cov(AY) &= \mathbb{E}\left[(AY- \mu_{AY})(AY- \mu_{AY})'\right] \\
    &= \mathbb{E}\left[(AY)(AY)'\right] \\
    &= \mathbb{E}\left[\begin{pmatrix}
2Y_1-Y_2 \\
3Y_2
\end{pmatrix} \begin{pmatrix}
2Y_1-Y_2 & 3Y_2
\end{pmatrix}\right] \\
&= \mathbb{E}\left[ \begin{pmatrix}
(2Y_1-Y_2)^2 & (2Y_1-Y_2)3Y_2\\
3Y_2(2Y_1-Y_2) & (3Y_2)^2
\end{pmatrix}\right] \\
&= \begin{pmatrix}
\mathbb{E}((2Y_1-Y_2)^2) & \mathbb{E}((2Y_1-Y_2)3Y_2)\\
\mathbb{E}(3Y_2(2Y_1-Y_2)) & \mathbb{E}((3Y_2)^2)
\end{pmatrix}
\end{align*}
Hallemos los valores esperados.
\begin{align*}
    \mathbb{E}((2Y_1-Y_2)^2) &= Var(2Y_1-Y_2) + (\mathbb{E}(2Y_1-Y_2))^2 \\
    &= 4Var(Y_1)+Var(-Y_2) +2cov(2Y_1,-Y_2)+ (2\mathbb{E}(Y_1) - \mathbb{E}(Y_2))^2 \\
    &= 4\cdot 1 + 4 + 2\cdot 2\cdot(-1)cov(Y_1,Y_2) + 0 \\
    &= 8 -4\cdot(-2) \\
    &= 16
\end{align*}
\begin{align*}
    \mathbb{E}((3Y_2)^2) &= Var(3Y_2) + (\mathbb{E}(3Y_2))^2 \\
    &= 9Var(Y_2) + (3\mathbb{E}(Y_2))^2 \\
    &= 9\cdot 4 + 0 \\
    &= 36
\end{align*}
\begin{align*}
    \mathbb{E}((2Y_1-Y_2)3Y_2) &= \mathbb{E}(6Y_1Y_2 - 3Y_2^2) \\
    &= 6\mathbb{E}(Y_1Y_2) - 3\mathbb{E}(Y_2^2) \\
    &= 6cov(Y_1,Y_2) + 6\mathbb{E}(Y_1)\mathbb{E}(Y_2) -3(var(Y_2) +(\mathbb{E}(Y_2))^2) \\
    &= 6\cdot(-2) + 0 - 3(4+0) \\
    &= -12 -12\\
    &= -24
\end{align*}
\begin{align*}
    \mathbb{E}(3Y_2(2Y_1-Y_2)) &= \mathbb{E}(6Y_2Y_1 - 3Y_2^2) \\
    &= 6\mathbb{E}(Y_2Y_1) - 3\mathbb{E}(Y_2^2) \\
    &= 6cov(Y_2,Y_1) + 6\mathbb{E}(Y_2)\mathbb{E}(Y_1) -3(var(Y_2) +(\mathbb{E}(Y_2))^2) \\
    &= 6\cdot(-2) + 0 - 3(4+0) \\
    &= -12 -12\\
    &= -24
\end{align*}
Entonces,
\begin{align*}
     cov(AY) &= \begin{pmatrix}
16 & -24 \\
-24 & 36
\end{pmatrix}
\end{align*}

Ahora encontremos $A\Sigma A'$

\begin{align*}
    A\Sigma A' &= \begin{pmatrix}
2 & -1 \\
0 & 3
\end{pmatrix} \begin{pmatrix}
1 & -2 \\
-2 & 4
\end{pmatrix} \begin{pmatrix}
2 & 0 \\
-1 & 3
\end{pmatrix} \\
&= \begin{pmatrix}
4 & -8 \\
-6 & 12
\end{pmatrix} \begin{pmatrix}
2 & 0 \\
-1 & 3
\end{pmatrix} \\
&= \begin{pmatrix}
16 & -24 \\
-24 & 36
\end{pmatrix}
\end{align*}